package com.crazyjiang.crazydemo.app.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.crazyjiang.crazydemo.mvp.model.entity.DaoGankEntity;
import com.crazyjiang.crazydemo.mvp.model.entity.Video;

import com.crazyjiang.crazydemo.app.greendao.DaoGankEntityDao;
import com.crazyjiang.crazydemo.app.greendao.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoGankEntityDaoConfig;
    private final DaoConfig videoDaoConfig;

    private final DaoGankEntityDao daoGankEntityDao;
    private final VideoDao videoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoGankEntityDaoConfig = daoConfigMap.get(DaoGankEntityDao.class).clone();
        daoGankEntityDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        daoGankEntityDao = new DaoGankEntityDao(daoGankEntityDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);

        registerDao(DaoGankEntity.class, daoGankEntityDao);
        registerDao(Video.class, videoDao);
    }
    
    public void clear() {
        daoGankEntityDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
    }

    public DaoGankEntityDao getDaoGankEntityDao() {
        return daoGankEntityDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

}
